// SRTP/SDES receiver for UniFi RTSPS streams (S6-11).
//
// UniFi's ?enableSrtp endpoint negotiates SDES (RFC 4568) — the SRTP
// master key is delivered in cleartext in the SDP via `a=crypto:`
// inline. There is no MIKEY, no key exchange, no Diffie-Hellman. The
// only crypto on the wire is the symmetric SRTP transform applied to
// each RTP packet by the camera; everything we need to decrypt and
// authenticate is in the SDP.
//
// Verified against the Python prototype in
// `C:\Projects\UniFi\tools\mikey_crack\` (scripts 8 / 9 / 11) which
// the MIKEY-RE-Chat ran end-to-end against the live Intercom and
// against the RFC 3711 Appendix B.3 test vectors.
//
// Why not pion/srtp: libsrtp / pion/srtp reject packets larger than
// ~2 KiB (`packet is too long`) — a compile-time limit that UniFi's
// up-to-65 KiB intra-frame TCP-interleaved packets routinely exceed.
// AES-CM is a stream cipher; size does not matter cryptographically.
// We implement the transform directly on top of crypto/aes + CTR mode,
// no third-party dependency, stdlib only.
//
// Scope today: VIDEO only (one SSRC, the single H.264 track UniFi
// advertises). No RTCP / SRTCP, no audio (AAC/Opus on tracks 0/1),
// no MKI, no key rotation. These are intentional out-of-scope per
// the S6-11 briefing.

package unifi

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/sha1"
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
	"sync"
)

// srtpAuthTagLen is the HMAC-SHA1-80 tag length in bytes — the suite
// UniFi negotiates via `a=crypto:1 AES_CM_128_HMAC_SHA1_80 ...`.
const srtpAuthTagLen = 10

// KDF labels per RFC 3711 §4.3.
const (
	srtpKDFLabelEnc  byte = 0x00 // session encryption key (16 B)
	srtpKDFLabelAuth byte = 0x01 // session authentication key (20 B)
	srtpKDFLabelSalt byte = 0x02 // session salt (14 B)
)

// Errors a receiver can produce on per-packet processing.
var (
	// ErrSRTPAuth is returned when the HMAC tag check fails. The
	// caller should drop the packet (and ideally rate-limit the
	// surrounding log).
	ErrSRTPAuth = errors.New("srtp: HMAC authentication failed")
	// ErrSRTPMalformed is returned for packets that aren't valid
	// RTP-on-the-wire (too short, wrong version, header overruns
	// the packet).
	ErrSRTPMalformed = errors.New("srtp: malformed packet")
)

// srtpKDF derives a session key from the SRTP master key + master
// salt per RFC 3711 §4.3.1 with the default key_derivation_rate=0
// (so key_id = label << 48).
//
// Verified byte-for-byte against the RFC 3711 Appendix B.3 test
// vectors — see TestSRTPKDF_RFC3711AppendixB3.
//
//	x         = master_salt (14 B), XORed with key_id on the LOWER 7 B
//	iv (16 B) = x || 0x0000
//	out       = AES-128-CTR(master_key, iv) zeros, truncated to outLen
//
// outLen is typically 16 (enc), 20 (auth), or 14 (salt).
func srtpKDF(masterKey, masterSalt []byte, label byte, outLen int) ([]byte, error) {
	if len(masterKey) != 16 {
		return nil, fmt.Errorf("srtp: master key must be 16 bytes, got %d", len(masterKey))
	}
	if len(masterSalt) != 14 {
		return nil, fmt.Errorf("srtp: master salt must be 14 bytes, got %d", len(masterSalt))
	}
	// x starts as a copy of the salt. key_id_bytes = (label << 48)
	// expressed as a 7-byte big-endian integer, i.e.
	// [label, 0, 0, 0, 0, 0, 0]. The XOR aligns key_id with the
	// LAST 7 bytes of the 14-byte salt — so only one byte actually
	// changes (the byte at index 7 gets XORed with label; the rest
	// XOR with zero, i.e. no change).
	iv := make([]byte, 16)
	copy(iv, masterSalt)
	iv[7] ^= label
	// iv[14..15] are already the required two zero bytes.

	return aesCMKeystream(masterKey, iv, outLen)
}

// aesCMKeystream returns the first nbytes of the AES-128-CTR keystream
// for the given key and 16-byte IV. Generated by encrypting a zero
// plaintext under counter mode — exactly the SRTP AES-CM transform.
func aesCMKeystream(key, iv []byte, nbytes int) ([]byte, error) {
	if len(iv) != 16 {
		return nil, fmt.Errorf("srtp: iv must be 16 bytes, got %d", len(iv))
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("srtp: aes cipher: %w", err)
	}
	out := make([]byte, nbytes)
	cipher.NewCTR(block, iv).XORKeyStream(out, out) // out is zero ⇒ result is the keystream
	return out, nil
}

// extractSDESVideoKey scans an SDP body for the video track's
// `a=crypto:` inline key and returns the decoded 30-byte master
// key (16 B) + master salt (14 B) concatenated as the Python
// prototype does. Lifetime / MKI metadata is discarded — we use one
// key per session.
//
// SDES line shape (RFC 4568 §9.2):
//
//	a=crypto:<tag> AES_CM_128_HMAC_SHA1_80 inline:<b64>|<lifetime>|<mki:length>
//
// We accept any tag and the standard suite. If the video section has
// multiple a=crypto: lines, the first one wins (UniFi only ships one).
// The returned slice is the raw secret — caller MUST NOT log it.
func extractSDESVideoKey(sdp []byte) ([]byte, error) {
	inVideo := false
	for _, raw := range strings.Split(string(sdp), "\n") {
		line := strings.TrimRight(raw, "\r ")
		if strings.HasPrefix(line, "m=video") {
			inVideo = true
			continue
		}
		if strings.HasPrefix(line, "m=") {
			inVideo = false
			continue
		}
		if !inVideo {
			continue
		}
		if !strings.HasPrefix(line, "a=crypto:") {
			continue
		}
		// Find the `inline:` token among the whitespace-separated fields.
		for _, field := range strings.Fields(line) {
			if !strings.HasPrefix(field, "inline:") {
				continue
			}
			payload := strings.TrimPrefix(field, "inline:")
			// Drop |lifetime|mki — anything after the first |.
			if i := strings.Index(payload, "|"); i >= 0 {
				payload = payload[:i]
			}
			raw, err := base64.StdEncoding.DecodeString(payload)
			if err != nil {
				return nil, fmt.Errorf("srtp: SDES inline base64 decode: %w", err)
			}
			if len(raw) != 30 {
				return nil, fmt.Errorf("srtp: SDES inline key has %d bytes, want 30 (16 master + 14 salt)", len(raw))
			}
			return raw, nil
		}
	}
	return nil, errors.New("srtp: no a=crypto: inline key found for video track")
}

// srtpReceiver is a stateful SRTP receiver for a single SSRC. It
// holds the three session keys derived from the SDES master key
// plus the rolling ROC (roll-over counter) and last seen sequence
// number — together these form the 48-bit packet index used by both
// the per-packet AES-CM IV and the HMAC tag.
//
// Concurrent calls are serialised on mu — the unifi.Source's RTP
// callback runs in a single gortsplib goroutine today, but the lock
// makes the receiver safe to share if a future teardown / log
// goroutine ever calls process from another goroutine.
type srtpReceiver struct {
	sessionKey  []byte // 16 B AES-CM encryption key
	authKey     []byte // 20 B HMAC-SHA1 authentication key
	sessionSalt []byte // 14 B AES-CM session salt

	mu      sync.Mutex
	roc     uint32 // 32-bit roll-over counter — combines with seq to form the 48-bit packet index
	lastSeq uint16
	seen    bool
}

// newSRTPReceiver derives the three session keys from the SDES master
// key + salt and returns a ready-to-use receiver.
func newSRTPReceiver(masterKey, masterSalt []byte) (*srtpReceiver, error) {
	sk, err := srtpKDF(masterKey, masterSalt, srtpKDFLabelEnc, 16)
	if err != nil {
		return nil, err
	}
	ak, err := srtpKDF(masterKey, masterSalt, srtpKDFLabelAuth, 20)
	if err != nil {
		return nil, err
	}
	ss, err := srtpKDF(masterKey, masterSalt, srtpKDFLabelSalt, 14)
	if err != nil {
		return nil, err
	}
	return &srtpReceiver{
		sessionKey:  sk,
		authKey:     ak,
		sessionSalt: ss,
	}, nil
}

// updateROC implements the simplified ROC update rule for ordered
// transports (RTSPS / TCP-interleaved): if the sequence number jumps
// backwards by more than 0x8000, treat it as a 16-bit wrap and bump
// the ROC. Returns the ROC value that applies to THIS packet (= the
// one used for both its IV and its HMAC).
//
// For UDP / out-of-order transports a more elaborate "guess where the
// packet falls" algorithm (RFC 3711 §3.3.1) would be needed. TCP
// delivers in order; this is sufficient.
//
// Verified against synthetic double-wrap scenarios — see
// TestSRTPReceiver_ROCWrap.
func (r *srtpReceiver) updateROC(seq uint16) uint32 {
	if !r.seen {
		r.lastSeq = seq
		r.seen = true
		return r.roc
	}
	if seq < r.lastSeq && r.lastSeq-seq > 0x8000 {
		r.roc++
	}
	r.lastSeq = seq
	return r.roc
}

// process decrypts and authenticates the given full SRTP-on-the-wire
// packet (RTP header + encrypted body + 10-byte HMAC-SHA1-80 tag).
//
// On success, returns the cleartext H.264 RTP payload (the body
// portion only — no RTP header, no auth tag). The caller can feed it
// directly into a standard H.264 RTP depacketizer.
//
// Returns ErrSRTPAuth if the HMAC check fails (caller drops the
// packet). Returns ErrSRTPMalformed for shape errors (too short,
// wrong version, header overruns).
func (r *srtpReceiver) process(packet []byte) ([]byte, error) {
	if len(packet) < 12+srtpAuthTagLen {
		return nil, ErrSRTPMalformed
	}
	if packet[0]>>6 != 2 { // RTP version must be 2
		return nil, ErrSRTPMalformed
	}
	cc := int(packet[0] & 0x0F)
	hdrLen := 12 + cc*4
	authedLen := len(packet) - srtpAuthTagLen
	if hdrLen > authedLen {
		return nil, ErrSRTPMalformed
	}

	seq := binary.BigEndian.Uint16(packet[2:4])
	// ssrc bytes for the IV are read from inside packet[8:12] below.

	r.mu.Lock()
	defer r.mu.Unlock()
	roc := r.updateROC(seq)

	// 1) Authenticate: HMAC-SHA1-80 over (packet without tag || ROC_BE).
	foundTag := packet[authedLen:]
	mac := hmac.New(sha1.New, r.authKey)
	mac.Write(packet[:authedLen])
	var rocBE [4]byte
	binary.BigEndian.PutUint32(rocBE[:], roc)
	mac.Write(rocBE[:])
	expected := mac.Sum(nil)[:srtpAuthTagLen]
	if !hmac.Equal(expected, foundTag) {
		return nil, ErrSRTPAuth
	}

	// 2) Decrypt the body with AES-128-CTR. The 128-bit IV is built
	// by XORing the session salt (left-padded to 16 bytes) with
	// (ssrc << 64) and (packet_index << 16), per RFC 3711 §4.1.1:
	//
	//   IV (128b)  = session_salt(112b, 0-padded to 128b)
	//              ^ (ssrc(32b) << 64)
	//              ^ (packet_index(48b) << 16)
	//
	// In byte-index form (big-endian, bytes [0..15]):
	//   bytes [0..13] = session_salt (then XOR with the layouts below)
	//   bytes [14..15] = 0
	//   bytes [4..7]   XOR= ssrc bytes
	//   bytes [8..13]  XOR= packet_index as 6 BE bytes
	iv := make([]byte, 16)
	copy(iv, r.sessionSalt)
	iv[4] ^= packet[8]
	iv[5] ^= packet[9]
	iv[6] ^= packet[10]
	iv[7] ^= packet[11]
	pktIndex := (uint64(roc) << 16) | uint64(seq) // 48-bit packet index
	iv[8] ^= byte(pktIndex >> 40)
	iv[9] ^= byte(pktIndex >> 32)
	iv[10] ^= byte(pktIndex >> 24)
	iv[11] ^= byte(pktIndex >> 16)
	iv[12] ^= byte(pktIndex >> 8)
	iv[13] ^= byte(pktIndex)

	body := packet[hdrLen:authedLen]
	ks, err := aesCMKeystream(r.sessionKey, iv, len(body))
	if err != nil {
		return nil, fmt.Errorf("srtp: keystream: %w", err)
	}
	clear := make([]byte, len(body))
	for i := range body {
		clear[i] = body[i] ^ ks[i]
	}
	return clear, nil
}
