// Package viewerstore is the single SQL writer for new rows in
// the `viewers` table and the matching service-port allocator.
//
// The package exists because TWO processes need to add a viewer:
//
//   - carvilon-server (in-process): the admin /a/web-viewers and
//     /a/esp-viewers handlers call internal/viewermanager.Manager,
//     which delegates to viewerstore.Insert.
//   - carvilon-cli (separate process, `esp adopt` subcommand): the
//     CLI opens the same SQLite file with database/sql and calls
//     viewerstore.Insert directly. It cannot reach the live
//     viewermanager goroutine through any other channel.
//
// Both call paths share this package so the column list, default
// handling, and timestamp semantics live in exactly one place. If
// a new viewers column ever becomes load-bearing, this is the one
// file to update; the absence of two parallel INSERT statements
// is what makes that safe.
//
// Token-hash semantics are NOT this package's concern. The ESP
// bearer token is generated by internal/auth/esptoken before
// Insert is called; this package only persists the hash. The
// one-shot cleartext-reveal lives in the caller (CLI prints once
// to stdout; the admin UI parks it in esp_pending_devices for the
// ESP to fetch).
package viewerstore

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// ServicePortStart is the first port the allocator hands out. Both
// the admin auto-allocator and the CLI fall back to this value
// when the viewers table is empty.
const ServicePortStart = 8100

// InsertSpec carries the column values for a new `viewers` row.
// All string fields are written as-is except PairedIntercomMAC
// (lowercased + trimmed). Empty strings become SQL NULL for
// nullable columns; PairedIntercomMAC is NOT NULL DEFAULT ''
// in the schema so an empty value is preserved as the empty
// string. AutoScreensaverSeconds == nil OR pointing at 0 becomes
// SQL NULL (0 is the same as "feature off").
//
// Insert does NOT validate; the caller is expected to have
// run its own input checks (MAC format, name length, Type ∈
// {"web","esp"}, etc.) before reaching this layer.
type InsertSpec struct {
	MAC                    string
	Name                   string
	ServicePort            uint16
	Type                   string
	LinkedUAUserID         string
	ESPModel               string
	ESPFwVersion           string
	DeviceTokenHash           string
	PairedIntercomMAC      string
	StreamProfile          string
	IdleViewMode           string
	AutoScreensaverSeconds *int
}

// Insert writes a new viewers row. The created_at and updated_at
// columns both get the `now` argument (caller-provided unix
// milliseconds) so tests can pin the timestamp. esp_pending is
// not in the column list; it falls back to its DDL default of 0.
func Insert(ctx context.Context, db *sql.DB, spec InsertSpec, now int64) error {
	_, err := db.ExecContext(ctx,
		`INSERT INTO viewers
		   (mac, name, service_port, type, linked_ua_user_id,
		    esp_model, esp_fw_version, device_token_hash,
		    paired_intercom_mac, stream_profile, idle_view_mode,
		    auto_screensaver_seconds,
		    created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		spec.MAC, spec.Name, int64(spec.ServicePort),
		spec.Type,
		nullableString(spec.LinkedUAUserID),
		nullableString(spec.ESPModel),
		nullableString(spec.ESPFwVersion),
		nullableString(spec.DeviceTokenHash),
		strings.ToLower(strings.TrimSpace(spec.PairedIntercomMAC)),
		nullableString(strings.TrimSpace(spec.StreamProfile)),
		nullableString(strings.TrimSpace(spec.IdleViewMode)),
		nullableInt(spec.AutoScreensaverSeconds),
		now, now,
	)
	if err != nil {
		return fmt.Errorf("viewerstore: insert: %w", err)
	}
	return nil
}

// NextFreeServicePort returns ServicePortStart for an empty table
// and MAX(service_port)+1 otherwise. The result is a uint16 to
// match the rest of the viewer-spec plumbing; nothing here checks
// for overflow because the auto-allocator gives up well before
// 64k ports.
func NextFreeServicePort(ctx context.Context, db *sql.DB) (uint16, error) {
	var maxPort scannedInt
	err := db.QueryRowContext(ctx,
		`SELECT COALESCE(MAX(service_port), 0) FROM viewers`,
	).Scan(&maxPort)
	if err != nil {
		return 0, fmt.Errorf("viewerstore: next free port: %w", err)
	}
	if maxPort.v < ServicePortStart {
		return ServicePortStart, nil
	}
	return uint16(maxPort.v + 1), nil
}

// nullableString is the standard "empty -> SQL NULL" helper. The
// nullable columns in the viewers table all use this convention.
func nullableString(s string) any {
	if s == "" {
		return nil
	}
	return s
}

// nullableInt mirrors nullableString for pointer-to-int fields:
// nil and 0 both become SQL NULL, anything else stores the int.
// AutoScreensaverSeconds uses this because 0 is the same as
// "feature off".
func nullableInt(p *int) any {
	if p == nil || *p == 0 {
		return nil
	}
	return int64(*p)
}

// scannedInt accepts the int64 / int variants the modernc.org
// sqlite driver returns for a COALESCE result. The wrapper exists
// so callers do not have to import database/sql just to handle
// the possible types.
type scannedInt struct{ v int64 }

func (n *scannedInt) Scan(src any) error {
	if src == nil {
		n.v = 0
		return nil
	}
	switch x := src.(type) {
	case int64:
		n.v = x
	case int:
		n.v = int64(x)
	default:
		return fmt.Errorf("viewerstore: unexpected service_port type %T", src)
	}
	return nil
}
